/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as TariffsRouteImport } from './routes/tariffs'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PublicOfferRouteImport } from './routes/public-offer'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OrderRouteImport } from './routes/order'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ApiRouteImport } from './routes/api'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NakrutkaIndexRouteImport } from './routes/nakrutka.index'
import { Route as SupportIdRouteImport } from './routes/support.$id'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as GuestOrderTokenRouteImport } from './routes/guest-order.$token'
import { Route as NakrutkaTypePlatformRouteImport } from './routes/nakrutka.$type.$platform'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const TariffsRoute = TariffsRouteImport.update({
  id: '/tariffs',
  path: '/tariffs',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicOfferRoute = PublicOfferRouteImport.update({
  id: '/public-offer',
  path: '/public-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NakrutkaIndexRoute = NakrutkaIndexRouteImport.update({
  id: '/nakrutka/',
  path: '/nakrutka/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIdRoute = SupportIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SupportRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestOrderTokenRoute = GuestOrderTokenRouteImport.update({
  id: '/guest-order/$token',
  path: '/guest-order/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const NakrutkaTypePlatformRoute = NakrutkaTypePlatformRouteImport.update({
  id: '/nakrutka/$type/$platform',
  path: '/nakrutka/$type/$platform',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/api': typeof ApiRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/public-offer': typeof PublicOfferRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRouteWithChildren
  '/tariffs': typeof TariffsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/guest-order/$token': typeof GuestOrderTokenRoute
  '/p/$slug': typeof PSlugRoute
  '/support/$id': typeof SupportIdRoute
  '/nakrutka/': typeof NakrutkaIndexRoute
  '/nakrutka/$type/$platform': typeof NakrutkaTypePlatformRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/api': typeof ApiRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/public-offer': typeof PublicOfferRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRouteWithChildren
  '/tariffs': typeof TariffsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/guest-order/$token': typeof GuestOrderTokenRoute
  '/p/$slug': typeof PSlugRoute
  '/support/$id': typeof SupportIdRoute
  '/nakrutka': typeof NakrutkaIndexRoute
  '/nakrutka/$type/$platform': typeof NakrutkaTypePlatformRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/api': typeof ApiRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/public-offer': typeof PublicOfferRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRouteWithChildren
  '/tariffs': typeof TariffsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/guest-order/$token': typeof GuestOrderTokenRoute
  '/p/$slug': typeof PSlugRoute
  '/support/$id': typeof SupportIdRoute
  '/nakrutka/': typeof NakrutkaIndexRoute
  '/nakrutka/$type/$platform': typeof NakrutkaTypePlatformRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/api'
    | '/faq'
    | '/login'
    | '/order'
    | '/privacy-policy'
    | '/public-offer'
    | '/register'
    | '/services'
    | '/sitemap.xml'
    | '/support'
    | '/tariffs'
    | '/terms-of-service'
    | '/guest-order/$token'
    | '/p/$slug'
    | '/support/$id'
    | '/nakrutka/'
    | '/nakrutka/$type/$platform'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/api'
    | '/faq'
    | '/login'
    | '/order'
    | '/privacy-policy'
    | '/public-offer'
    | '/register'
    | '/services'
    | '/sitemap.xml'
    | '/support'
    | '/tariffs'
    | '/terms-of-service'
    | '/guest-order/$token'
    | '/p/$slug'
    | '/support/$id'
    | '/nakrutka'
    | '/nakrutka/$type/$platform'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/api'
    | '/faq'
    | '/login'
    | '/order'
    | '/privacy-policy'
    | '/public-offer'
    | '/register'
    | '/services'
    | '/sitemap.xml'
    | '/support'
    | '/tariffs'
    | '/terms-of-service'
    | '/guest-order/$token'
    | '/p/$slug'
    | '/support/$id'
    | '/nakrutka/'
    | '/nakrutka/$type/$platform'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  ApiRoute: typeof ApiRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  OrderRoute: typeof OrderRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PublicOfferRoute: typeof PublicOfferRoute
  RegisterRoute: typeof RegisterRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRouteWithChildren
  TariffsRoute: typeof TariffsRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  GuestOrderTokenRoute: typeof GuestOrderTokenRoute
  PSlugRoute: typeof PSlugRoute
  NakrutkaIndexRoute: typeof NakrutkaIndexRoute
  NakrutkaTypePlatformRoute: typeof NakrutkaTypePlatformRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tariffs': {
      id: '/tariffs'
      path: '/tariffs'
      fullPath: '/tariffs'
      preLoaderRoute: typeof TariffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-offer': {
      id: '/public-offer'
      path: '/public-offer'
      fullPath: '/public-offer'
      preLoaderRoute: typeof PublicOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nakrutka/': {
      id: '/nakrutka/'
      path: '/nakrutka'
      fullPath: '/nakrutka/'
      preLoaderRoute: typeof NakrutkaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/$id': {
      id: '/support/$id'
      path: '/$id'
      fullPath: '/support/$id'
      preLoaderRoute: typeof SupportIdRouteImport
      parentRoute: typeof SupportRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-order/$token': {
      id: '/guest-order/$token'
      path: '/guest-order/$token'
      fullPath: '/guest-order/$token'
      preLoaderRoute: typeof GuestOrderTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nakrutka/$type/$platform': {
      id: '/nakrutka/$type/$platform'
      path: '/nakrutka/$type/$platform'
      fullPath: '/nakrutka/$type/$platform'
      preLoaderRoute: typeof NakrutkaTypePlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SupportRouteChildren {
  SupportIdRoute: typeof SupportIdRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportIdRoute: SupportIdRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  ApiRoute: ApiRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  OrderRoute: OrderRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PublicOfferRoute: PublicOfferRoute,
  RegisterRoute: RegisterRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRouteWithChildren,
  TariffsRoute: TariffsRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  GuestOrderTokenRoute: GuestOrderTokenRoute,
  PSlugRoute: PSlugRoute,
  NakrutkaIndexRoute: NakrutkaIndexRoute,
  NakrutkaTypePlatformRoute: NakrutkaTypePlatformRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
